framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: ~

    #esi: true
    #fragments: true
    php_errors:
        log: true
    cache:

parameters:
    app.path.brand_images: /img/brands
    app.path.category_images: /img/categories
    app.path.product_images: /img/products



vich_uploader:

    mappings:
        brand_images:
            uri_prefix:         '%app.path.brand_images%'
            upload_destination: '%kernel.root_dir%/../public/img/brands'
        category_images:
            uri_prefix:         '%app.path.category_images%'
            upload_destination: '%kernel.root_dir%/../public/img/categories'
        product_images:
            uri_prefix:         '%app.path.product_images%'
            upload_destination: '%kernel.root_dir%/../public/img/products'

