liip_imagine :

  # configure resolvers
  resolvers :

      # setup the default resolver
      default :

          # use the default web path
          web_path :
              web_root: "%kernel.project_dir%/public"
              cache_prefix: "img/thumbs"
  loaders:
      default:
          filesystem:
              data_root: "%kernel.project_dir%/public/"


  driver:               "gd"
  cache:                default
  data_loader:          default
  default_image:        null
  controller:
      filter_action:         liip_imagine.controller:filterAction
      filter_runtime_action: liip_imagine.controller:filterRuntimeAction


  filter_sets :
      cache : ~
      catalog_item_main:
          quality : 100
          filters :
              thumbnail  : { size : [160, 160], mode: inset  }
              background: { size: [160, 160], position: center, color: '#FFFFFF' }

      catalog_product:
          quality : 100
          filters :
              thumbnail  : { size : [250, 200], mode : outbound }
              background: { size: [250, 200], position: center, color: '#FFFFFF' }

      product_main:
          quality : 100
          filters :
              thumbnail  : { size : [520, 400], mode : outbound }
              background: { size: [520, 400], position: center, color: '#FFFFFF' }

      product_nav:
          quality : 100
          filters :
              thumbnail  : { size : [120, 90], mode : outbound }
              background: { size: [120, 90], position: center, color: '#FFFFFF' }
