swiftmailer:
    transport:            sendmail
    username:             ~
    password:             ~
    host:                 localhost
    antiflood:
            threshold:            99
            sleep:                0
