easy_admin:
    entities:
        Brand:
            class: App\Entity\Brand
            controller: App\Controller\CMS\BrandController
            templates:
                list: 'easy_admin/default/Brand/list.html.twig'
            list:
                actions:
                    - { name: 'model', label: 'Models', type: 'method'}
                fields:
                    - { property: 'name', type: 'text' }
                    - { property: 'active', type: 'toggle' }
                    - { property: 'image', type: 'image', base_path: '/img/brands' }
            edit:
                fields:
                    - { property: 'active', label: 'Active'}
                    - { property: 'name', type: 'text' }
                    - { property: 'alias', type: 'text' }
                    - { property: 'imageFile', type: 'vich_image'}
                    - { property: 'description', type: 'textarea', css_class: "ckeditor"}
            new:
                fields:
                    - { property: 'active',label: 'Active'}
                    - { property: 'name', type: 'text' }
                    - { property: 'alias', type: 'text' }
                    - { property: 'imageFile', type: 'vich_image'}
                    - { property: 'description', type: 'textarea', css_class: "ckeditor"}