easy_admin:
    site_name: 'Part Store'
    design:
        brand_color: '#333'
        templates:
            list: 'easy_admin/list.html.twig'
        menu:
            - Category
            - Brand
            - Product
            - { entity: 'Product',label: 'Import', params: { action: 'import' } }